load("//MyProject.xcodeproj/XCHammerAssets:Hammer.bzl", "export_entitlements")
export_entitlements(
  name = "DummyProject-DummyProject_entitlements",
  entitlements = None,
  provisioning_profile = None,
  bundle_id = "bang.example.ios-app",
  platform_type = "ios"
)